import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
function subtractNotice(endDate:string,value:number,unit:string){
 if(!/^\d{4}-\d{2}-\d{2}$/.test(String(endDate||''))||!Number.isFinite(value)||value<=0)return "";
 const [y,m,d]=endDate.split('-').map(Number); let dt:Date;
 if(unit==='day'||unit==='days')dt=new Date(Date.UTC(y,m-1,d-value));
 else if(unit==='week'||unit==='weeks')dt=new Date(Date.UTC(y,m-1,d-(value*7)));
 else if(unit==='month'||unit==='months'){
   const total=y*12+(m-1)-value, ty=Math.floor(total/12), tm=((total%12)+12)%12;
   const last=new Date(Date.UTC(ty,tm+1,0)).getUTCDate(); dt=new Date(Date.UTC(ty,tm,Math.min(d,last)));
 } else if(unit==='year'||unit==='years'){
   const ty=y-value,last=new Date(Date.UTC(ty,m,0)).getUTCDate(); dt=new Date(Date.UTC(ty,m-1,Math.min(d,last)));
 } else return "";
 return dt.toISOString().slice(0,10);
}
serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{
 const key=Deno.env.get("OPENAI_API_KEY");if(!key)throw new Error("OPENAI_API_KEY belum diset di Supabase Secrets");
 const {filename,mimeType,base64,documentType='lease'}=await req.json();if(!base64)throw new Error("File kosong");
 const prompts:any={
 lease:`Baca akta/perjanjian sewa atau dokumen tanah Indonesia ini dengan sangat teliti. Kembalikan HANYA JSON valid, tanpa markdown. Jangan menebak data yang tidak terlihat; gunakan string kosong, 0, atau array kosong. Semua tanggal harus YYYY-MM-DD. Semua nilai uang harus angka tanpa Rp/pemisah ribuan.

KHUSUS PERPANJANGAN: cari seluruh klausul yang mengatur pemberitahuan/permohonan perpanjangan masa sewa. Jika klausul menyatakan batas relatif terhadap akhir masa sewa, misalnya "6 bulan sebelum berakhir", ekstrak angka dan satuannya. renewalNoticeValue harus angka (contoh 6 atau 90), renewalNoticeUnit hanya salah satu: day, week, month, year. renewalNoticeText harus berisi ringkasan redaksi asli klausul. renewalNoticePage berisi halaman sumber yang TEPAT bila terlihat, misalnya "Pasal 1, halaman akta 6". renewalTerm WAJIB merangkum seluruh hak dan ketentuan perpanjangan secara substantif, bukan hanya durasinya: siapa yang dapat meminta perpanjangan, cara/bentuk pemberitahuan, batas waktu, apakah persetujuan otomatis atau bergantung pada persetujuan/hak pihak lain, serta periode perpanjangan bila memang disebut. Jika periode perpanjangan tidak disebut, jangan mengarang durasi; tetap isi renewalTerm dengan ketentuan yang benar-benar disebut. Contoh: "Pihak Kedua dapat mengajukan perpanjangan secara tertulis paling lambat 6 bulan sebelum berakhir; persetujuan sepenuhnya merupakan hak Pihak Pertama; periode perpanjangan tidak ditentukan." Jika dokumen menyebut tanggal deadline secara eksplisit, isi renewalNotice dengan tanggal itu. Jika hanya menyebut jangka relatif dan tanggal akhir sewa tersedia, JANGAN menebak tanggal renewalNotice; server akan menghitungnya secara deterministik dari end. Bedakan klausul PERPANJANGAN dari klausul PENGAKHIRAN/TERMINASI; jangan memakai masa pemberitahuan pengakhiran sebagai deadline perpanjangan. Jika ada klausul pengakhiran dini, masukkan terpisah ke clauses dengan title yang jelas seperti "Pengakhiran sebelum waktunya", termasuk notice period-nya, tanpa memengaruhi renewalNotice/renewalTerm. Jika tidak ada hak/ketentuan perpanjangan, kosongkan field-field perpanjangan. KHUSUS sourcePages: jangan isi dengan seluruh rentang dokumen seperti "1-27" atau "Sampul; 1-27". Isi hanya halaman-halaman utama yang benar-benar menjadi sumber data penting yang diekstrak, terutama identitas/objek sewa, jangka waktu dan perpanjangan, harga/pembayaran, serta klausul penting. Gunakan nomor halaman akta yang tercetak bila terlihat; untuk klausul perpanjangan utamakan format seperti "Pasal 1, halaman akta 6". Jika beberapa halaman penting, pisahkan dengan titik koma.

KHUSUS LUAS AKTA SEWA: leaseLandArea dan leaseBuildingArea hanya boleh diisi dari luas yang dinyatakan sebagai objek sewa dalam akta ini. Jangan menyalin luas dari sertifikat atau PBB yang hanya disebut sebagai dasar/lampiran.\n\nStruktur JSON persis: {"tenant":"","lessor":"","asset":"","propertyAddress":"","propertyArea":"","leaseLandArea":0,"leaseBuildingArea":0,"deedNo":"","deedDate":"","start":"","end":"","rent":0,"deposit":0,"renewalNotice":"","renewalNoticeValue":0,"renewalNoticeUnit":"","renewalNoticeText":"","renewalNoticePage":"","renewalTerm":"","sourcePages":"","notes":"","contacts":[{"role":"Pihak Pertama|Pihak Kedua|Notaris|Lainnya","name":"","phone":"","email":""}],"bankAccounts":[{"purpose":"","bank":"","account":"","holder":""}],"landRights":[{"type":"HGB|HM|SHM|Hak Pakai|Lainnya","number":"","area":"","end":""}],"payments":[{"due":"","amount":0,"label":""}],"clauses":[{"title":"","detail":"","page":"","importance":"Penting|Normal"}]}. Ringkas notes hanya untuk informasi penting yang tidak cocok ke field lain. Untuk clauses prioritaskan perpanjangan, pengakhiran, denda, pajak, pemeliharaan, larangan pengalihan/sublease, force majeure, serah terima, deposit, kewajiban para pihak, dan sengketa. Cantumkan halaman sumber bila dapat dikenali.`,
 land_title:`Baca dokumen Sertifikat/Akta Tanah Indonesia ini dengan sangat teliti. Kembalikan HANYA JSON valid tanpa markdown. Jangan menebak. Data luas harus hanya berasal dari dokumen tanah ini, bukan dari Akta Sewa atau PBB. Semua tanggal YYYY-MM-DD. Untuk SHM/HM yang tidak memiliki masa berakhir, validUntil harus string kosong. Struktur persis: {"rightType":"HGB|SHGB|SHM|HM|Hak Pakai|Lainnya","certificateNo":"","holderName":"","landArea":0,"validUntil":"","address":"","surveyNo":"","surveyDate":"","notes":""}. WAJIB cari bagian berjudul SURAT UKUR pada seluruh halaman. Jika bagian itu terlihat, isi surveyNo dari nomor yang tercetak tepat pada bagian SURAT UKUR dan surveyDate dari tanggal yang tercetak tepat pada bagian itu. Jangan membiarkan surveyNo/surveyDate kosong jika teksnya terbaca. Bedakan dari nomor/tanggal sertifikat, tanggal pembukuan, dan nomor dasar pendaftaran. Jika ada NIB, masukkan ke notes dengan awalan 'NIB:'. notes hanya untuk informasi penting lain dari dokumen.`,
 pbb:`Baca SPPT PBB Indonesia ini dengan sangat teliti. Kembalikan HANYA JSON valid tanpa markdown. Jangan menebak. Semua angka luas dan NJOP harus hanya berasal dari SPPT PBB ini; jangan mengambil dari Sertifikat Tanah atau Akta Sewa. Semua tanggal YYYY-MM-DD dan uang berupa angka tanpa Rp/pemisah ribuan. Struktur persis: {"nop":"","taxpayerName":"","objectAddress":"","taxYear":0,"landArea":0,"buildingArea":0,"landNjopM2":0,"landNjopTotal":0,"buildingNjopM2":0,"buildingNjopTotal":0,"totalNjop":0,"taxDue":0,"dueDate":"","notes":""}. Jika SPPT hanya menampilkan NJOP per m2 dan luas, boleh hitung total NJOP tanah/bangunan secara aritmetika; jangan mengarang data lain.`
 }; const prompt=prompts[documentType]||prompts.lease
 const isImage=String(mimeType||'').startsWith('image/');
 const content:any[]=[{type:"input_text",text:prompt}];
 if(isImage)content.push({type:"input_image",image_url:`data:${mimeType};base64,${base64}`,detail:"high"});
 else content.push({type:"input_file",filename:filename||"akta.pdf",file_data:`data:${mimeType||'application/pdf'};base64,${base64}`});
 const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Authorization":`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-5.6",input:[{role:"user",content}]})});
 const raw=await r.json();if(!r.ok)throw new Error(raw?.error?.message||`OpenAI error ${r.status}`);
 const text=raw.output?.flatMap((o:any)=>o.content||[]).find((c:any)=>c.type==="output_text")?.text||raw.output_text||"";
 let clean=String(text).trim().replace(/^```json\s*/i,'').replace(/```$/,'').trim();let data;try{data=JSON.parse(clean)}catch{throw new Error("AI mengembalikan hasil yang bukan JSON valid")}
 const noticeValue=Number(data?.renewalNoticeValue||0),noticeUnit=String(data?.renewalNoticeUnit||'').toLowerCase();
 if(data?.end&&noticeValue>0&&noticeUnit){const calculated=subtractNotice(String(data.end),noticeValue,noticeUnit);if(calculated)data.renewalNotice=calculated}
 return new Response(JSON.stringify({data}),{headers:{...cors,"Content-Type":"application/json"}});
}catch(e){return new Response(JSON.stringify({error:e.message||String(e)}),{status:400,headers:{...cors,"Content-Type":"application/json"}})}});
