const KEY='sewaAktaV1';let data=[],edit=-1,currentUser=null;const $=s=>document.querySelector(s);const fmt=n=>n?new Intl.NumberFormat('id-ID').format(n):'-';const date=s=>s?new Date(s+'T00:00:00'):null;const days=s=>s?Math.ceil((date(s)-new Date())/86400000):999999;
const cfg=window.SEWA_CONFIG||{};const configured=cfg.supabaseUrl&&!cfg.supabaseUrl.includes('PASTE_')&&cfg.supabaseKey&&!cfg.supabaseKey.includes('PASTE_');const sb=configured?window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseKey):null;
function storageKey(){return currentUser?`${KEY}:${currentUser.id}`:KEY}
function rowToApp(r){return {id:r.id,tenant:r.tenant||'',asset:r.asset||'',deedNo:r.deed_no||'',deedDate:r.deed_date||'',start:r.start_date||'',end:r.end_date||'',rent:Number(r.rent||0),renewalNotice:r.renewal_notice||'',pic1:r.pic1||'',phone1:r.phone1||'',pic2:r.pic2||'',phone2:r.phone2||'',bank:r.bank||'',account:r.account||'',accountName:r.account_name||'',hgbNo:r.hgb_no||'',hgbEnd:r.hgb_end||'',docUrl:r.doc_url||'',notes:r.notes||'',payments:Array.isArray(r.payments)?r.payments:[]}}
function appToRow(x){return {user_id:currentUser.id,tenant:x.tenant||'',asset:x.asset||'',deed_no:x.deedNo||null,deed_date:x.deedDate||null,start_date:x.start||null,end_date:x.end||null,rent:Number(x.rent||0),renewal_notice:x.renewalNotice||null,pic1:x.pic1||'',phone1:x.phone1||'',pic2:x.pic2||'',phone2:x.phone2||'',bank:x.bank||'',account:x.account||'',account_name:x.accountName||'',hgb_no:x.hgbNo||'',hgb_end:x.hgbEnd||null,doc_url:x.docUrl||'',notes:x.notes||'',payments:x.payments||[],updated_at:new Date().toISOString()}}
async function loadData(){
  const {data:rows,error}=await sb.from('contracts').select('*').order('created_at',{ascending:false});
  if(error){$('#authMsg').textContent='Database gagal: '+error.message; data=[]; render(); return}
  data=(rows||[]).map(rowToApp); render();
}
async function saveContract(x){
  const row=appToRow(x);
  let result;
  if(x.id) result=await sb.from('contracts').update(row).eq('id',x.id).select().single();
  else result=await sb.from('contracts').insert(row).select().single();
  if(result.error) throw result.error;
  await loadData();
}
function setSession(session){currentUser=session?.user||null;$('#authScreen').hidden=!!currentUser;$('#appShell').hidden=!currentUser;if(currentUser){$('#userEmail').textContent=currentUser.email||'';loadData()}}
async function initAuth(){if(!configured){$('#authMsg').innerHTML='<b>Belum dikonfigurasi.</b> Isi config.js dengan Supabase URL dan Publishable/anon key.';return}try{const {data:{session},error}=await sb.auth.getSession();if(error)throw error;setSession(session);sb.auth.onAuthStateChange((_event,session)=>setSession(session))}catch(err){$('#authMsg').textContent='Koneksi Supabase gagal: '+(err?.message||String(err))}}
$('#loginForm').onsubmit=async e=>{e.preventDefault();if(!sb)return;$('#authMsg').textContent='Memeriksa...';try{const {error}=await sb.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});$('#authMsg').textContent=error?'Login gagal: '+error.message:''}catch(err){$('#authMsg').textContent='Koneksi gagal: '+(err?.message||String(err))}};$('#logoutBtn').onclick=async()=>{await sb.auth.signOut()};
function render(){if(!currentUser)return;let q=$('#search').value.toLowerCase(),now=new Date();$('#stats').innerHTML=`<div class=stat><b>${data.length}</b><span>Kontrak tercatat</span></div><div class=stat><b>${data.filter(x=>date(x.end)>now).length}</b><span>Kontrak aktif</span></div><div class=stat><b>${data.filter(x=>days(x.end)<=365&&days(x.end)>=0).length}</b><span>Berakhir ≤ 1 tahun</span></div><div class=stat><b>${data.filter(x=>days(x.hgbEnd)<=730&&days(x.hgbEnd)>=0).length}</b><span>HGB ≤ 2 tahun</span></div>`;let a=[];data.forEach(x=>{x.payments?.forEach(p=>{let d=days(p.due);if(d>=0&&d<=90)a.push([d,`Pembayaran ${x.tenant}: Rp${fmt(p.amount)} — ${p.due}`])});let d=days(x.renewalNotice);if(d>=0&&d<=365)a.push([d,`Deadline perpanjangan ${x.tenant} — ${x.renewalNotice}`]);d=days(x.hgbEnd);if(d>=0&&d<=730)a.push([d,`HGB ${x.hgbNo||x.asset} berakhir ${x.hgbEnd} — mulai proses perpanjangan`])});a.sort((a,b)=>a[0]-b[0]);$('#alerts').innerHTML=a.length?a.map(x=>`<div class=warning><b>${x[0]} hari lagi</b> · ${x[1]}</div>`).join(''):'<div class=muted>Belum ada agenda yang masuk periode peringatan.</div>';$('#cards').innerHTML=data.map((x,i)=>[x,i]).filter(([x])=>JSON.stringify(x).toLowerCase().includes(q)).map(([x,i])=>`<article class=card><div><h3>${x.tenant}</h3><div>${x.asset}</div><div class=muted>Akta ${x.deedNo||'-'} · ${x.start||'-'} s/d ${x.end||'-'}</div></div><div><span class="pill ${days(x.end)<180?'danger':days(x.end)<365?'warn':''}">${days(x.end)>=0?'AKTIF':'SELESAI'}</span><div class=muted>Rp${fmt(x.rent)}</div><div class=muted>PIC: ${x.pic2||'-'} · ${x.phone2||'-'}</div><div class=muted>${x.bank||'-'} · ${x.accountName||'-'}</div></div><div><button onclick="openEdit(${i})">Buka / Edit</button></div></article>`).join('')}
function openEdit(i=-1){edit=i;let x=i>=0?data[i]:{};$('#form').reset();[...$('#form').elements].forEach(e=>{if(e.name&&x[e.name]!=null)e.value=x[e.name]});$('#payments').innerHTML='';(x.payments||[]).forEach(p=>pay(p));$('#dlg').showModal()}window.openEdit=openEdit;function pay(p={}){$('#payments').insertAdjacentHTML('beforeend',`<div class=payrow><input type=date class=due value="${p.due||''}"><input type=number class=amount placeholder="Nominal Rp" value="${p.amount||''}"><button type=button class=secondary onclick="this.parentElement.remove()">−</button></div>`)}
$('#addBtn').onclick=()=>openEdit();$('#cancel').onclick=()=>$('#dlg').close();$('#addPayment').onclick=()=>pay();$('#search').oninput=render;$('#form').onsubmit=async e=>{e.preventDefault();let x=Object.fromEntries(new FormData(e.target));x.rent=Number(x.rent||0);x.payments=[...document.querySelectorAll('.payrow')].map(r=>({due:r.querySelector('.due').value,amount:Number(r.querySelector('.amount').value||0)})).filter(p=>p.due||p.amount);if(edit>=0&&data[edit]?.id)x.id=data[edit].id;const btn=e.submitter;try{if(btn)btn.disabled=true;await saveContract(x);$('#dlg').close()}catch(err){alert('Gagal menyimpan ke Supabase: '+(err?.message||String(err)))}finally{if(btn)btn.disabled=false}};initAuth();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
