let data=[],edit=-1,currentUser=null;const $=s=>document.querySelector(s);const fmt=n=>n?new Intl.NumberFormat('id-ID',{maximumFractionDigits:2}).format(n):'-';
function parseMoney(v){if(typeof v==='number')return v;if(!v)return 0;let s=String(v).trim().replace(/\s/g,'').replace(/^Rp/i,'');if(s.includes(',')&&s.includes('.')){s=s.replace(/\./g,'').replace(',','.')}else if(s.includes(',')){s=s.replace(',','.')}else if((s.match(/\./g)||[]).length>1){s=s.replace(/\./g,'')}return Number(s.replace(/[^0-9.-]/g,''))||0}
function moneyDisplay(v){const n=parseMoney(v);return n?`Rp ${new Intl.NumberFormat('id-ID',{minimumFractionDigits:Number.isInteger(n)?0:2,maximumFractionDigits:2}).format(n)}`:''}
function moneyRaw(v){const n=parseMoney(v);return n?String(n):''}
function bindMoneyInput(el,onchange){if(!el||el.dataset.moneyBound)return;el.dataset.moneyBound='1';el.addEventListener('focus',()=>{el.value=moneyRaw(el.value);setTimeout(()=>el.select(),0)});el.addEventListener('blur',()=>{el.value=moneyDisplay(el.value);if(onchange)onchange()});el.addEventListener('input',()=>{if(onchange)onchange()});}
const date=s=>s?new Date(s+'T00:00:00'):null;const days=s=>s?Math.ceil((date(s)-new Date())/86400000):999999;const cfg=window.SEWA_CONFIG||{};const configured=cfg.supabaseUrl&&!cfg.supabaseUrl.includes('PASTE_')&&cfg.supabaseKey&&!cfg.supabaseKey.includes('PASTE_');const sb=configured&&window.supabase?window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}):null;
function status(m,k=''){const e=$('#authMsg');if(e){e.textContent=m;e.dataset.kind=k}}function withTimeout(p,ms,l){return Promise.race([p,new Promise((_,r)=>setTimeout(()=>r(new Error(l||'Timeout')),ms))])}
function rowToApp(r){return{id:r.id,tenant:r.tenant||'',lessor:r.lessor||'',asset:r.asset||'',propertyAddress:r.property_address||'',propertyArea:r.property_area||'',deedNo:r.deed_no||'',deedDate:r.deed_date||'',start:r.start_date||'',end:r.end_date||'',rent:Number(r.rent||0),deposit:Number(r.deposit||0),renewalNotice:r.renewal_notice||'',renewalTerm:r.renewal_term||'',docUrl:r.doc_url||'',notes:r.notes||'',payments:r.payments||[],contacts:r.contacts||[],bankAccounts:r.bank_accounts||[],landRights:r.land_rights||[],clauses:r.clauses||[],verificationStatus:r.verification_status||'perlu_verifikasi',sourcePages:r.source_pages||''}}
function appToRow(x){return{user_id:currentUser.id,tenant:x.tenant||'',lessor:x.lessor||'',asset:x.asset||'',property_address:x.propertyAddress||'',property_area:x.propertyArea||'',deed_no:x.deedNo||null,deed_date:x.deedDate||null,start_date:x.start||null,end_date:x.end||null,rent:parseMoney(x.rent),deposit:parseMoney(x.deposit),renewal_notice:x.renewalNotice||null,renewal_term:x.renewalTerm||'',doc_url:x.docUrl||'',notes:x.notes||'',payments:x.payments||[],contacts:x.contacts||[],bank_accounts:x.bankAccounts||[],land_rights:x.landRights||[],clauses:x.clauses||[],verification_status:x.verificationStatus||'perlu_verifikasi',source_pages:x.sourcePages||'',updated_at:new Date().toISOString()}}
async function loadData(){try{const {data:r,error}=await withTimeout(sb.from('contracts').select('*').order('created_at',{ascending:false}),12000,'Database tidak merespons.');if(error)throw error;data=(r||[]).map(rowToApp);render()}catch(e){data=[];render();alert('Data gagal dibaca: '+e.message)}}
function openDashboard(s){currentUser=s?.user;if(!currentUser)return;$('#authScreen').style.display='none';$('#appShell').hidden=false;$('#appShell').style.display='block';$('#userEmail').textContent=currentUser.email||'';loadData()}function showLogin(){currentUser=null;$('#appShell').hidden=true;$('#appShell').style.display='none';$('#authScreen').hidden=false;$('#authScreen').style.display='grid'}
async function initAuth(){showLogin();if(!configured)return status('Konfigurasi Supabase belum lengkap.','error');try{const r=await withTimeout(sb.auth.getSession(),10000,'Pemeriksaan session timeout.');if(r.data?.session)return openDashboard(r.data.session);status('Supabase siap. Silakan masuk.')}catch(e){status('Pemeriksaan awal gagal: '+e.message,'error')}sb.auth.onAuthStateChange((ev,s)=>{if(s)openDashboard(s);else if(ev==='SIGNED_OUT')showLogin()})}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;status('Menghubungi Supabase…');try{const r=await withTimeout(sb.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value}),15000,'Supabase tidak memberi respons.');if(r.error)throw r.error;if(!r.data?.session)throw new Error('Session tidak ditemukan');openDashboard(r.data.session)}catch(x){status('Login gagal: '+x.message,'error')}finally{b.disabled=false}};$('#logoutBtn').onclick=async()=>{await sb.auth.signOut();showLogin()};
async function saveContract(x){let r=x.id?await sb.from('contracts').update(appToRow(x)).eq('id',x.id).select().single():await sb.from('contracts').insert(appToRow(x)).select().single();if(r.error)throw r.error;await loadData()}
function nearestHgb(x){let ds=(x.landRights||[]).map(l=>l.end).filter(Boolean).sort();return ds[0]||''}
function render(){if(!currentUser)return;let q=$('#search').value.toLowerCase(),now=new Date();let overdue=0,unpaid90=0,contract180=0,hgb730=0;let a=[];
function pushAlert(day,text,type='normal',tag=''){a.push([day,text,type,tag])}
data.forEach(x=>{
  (x.payments||[]).forEach(p=>{if(p.status==='paid'||!p.due)return;let d=days(p.due);if(d<0){overdue++;pushAlert(d,`Pembayaran ${x.tenant}: Rp${fmt(p.amount)} — jatuh tempo ${p.due}`,'overdue','PEMBAYARAN')}else if(d<=90){unpaid90++;pushAlert(d,`Pembayaran ${x.tenant}: Rp${fmt(p.amount)} — jatuh tempo ${p.due}`,d<=30?'urgent':'due','PEMBAYARAN')}});
  let endDays=days(x.end);if(x.end){if(endDays<0)pushAlert(endDays,`Kontrak ${x.tenant} telah berakhir pada ${x.end}`,'overdue','KONTRAK');else if(endDays<=180){contract180++;pushAlert(endDays,`Kontrak ${x.tenant} berakhir ${x.end}. Siapkan perpanjangan / kontrak baru.`,endDays<=60?'urgent':'normal','KONTRAK')}}
  let d=days(x.renewalNotice);if(x.renewalNotice){if(d<0&&endDays>=0)pushAlert(d,`Deadline pemberitahuan perpanjangan ${x.tenant} sudah lewat — ${x.renewalNotice}`,'overdue','PERPANJANGAN');else if(d>=0&&d<=365)pushAlert(d,`Deadline pemberitahuan perpanjangan ${x.tenant} — ${x.renewalNotice}`,d<=60?'urgent':'normal','PERPANJANGAN')}
  (x.landRights||[]).forEach(l=>{if(!l.end)return;d=days(l.end);let label=`${l.type||'HGB'} ${l.number||x.asset}`;if(d<0)pushAlert(d,`${label} telah berakhir pada ${l.end}`,'overdue','HAK TANAH');else if(d<=730){hgb730++;pushAlert(d,`${label} berakhir ${l.end}. Mulai proses perpanjangan.`,d<=365?'urgent':'hgb','HAK TANAH')}})
});
$('#stats').innerHTML=`<div class=stat><b>${data.length}</b><span>Kontrak tercatat</span></div><div class=stat><b>${overdue}</b><span>Pembayaran terlambat</span></div><div class=stat><b>${contract180}</b><span>Kontrak ≤ 6 bulan</span></div><div class=stat><b>${hgb730}</b><span>Hak tanah ≤ 2 tahun</span></div>`;
a.sort((x,y)=>x[0]-y[0]);$('#alerts').innerHTML=a.length?a.map(x=>{let when=x[0]<0?`TERLAMBAT ${Math.abs(x[0])} HARI`:x[0]===0?'HARI INI':`${x[0]} HARI LAGI`;return `<div class="warning ${x[2]}"><div class=warning-head><span class=warning-tag>${x[3]}</span><b>${when}</b></div><div>${x[1]}</div></div>`}).join(''):'<div class=muted>Belum ada agenda yang masuk periode peringatan.</div>';
$('#cards').innerHTML=data.map((x,i)=>[x,i]).filter(([x])=>JSON.stringify(x).toLowerCase().includes(q)).map(([x,i])=>{const paid=(x.payments||[]).filter(p=>p.status==='paid').length,total=(x.payments||[]).length;return `<article class=card><div><h3>${x.tenant}</h3><div>${x.asset}</div><div class=muted>${x.lessor?'Pemilik: '+x.lessor+' · ':''}Akta ${x.deedNo||'-'} · ${x.start||'-'} s/d ${x.end||'-'}</div><div class=detail-lines><span>Nilai sewa: Rp${fmt(x.rent)}</span><span>${total?paid+'/'+total+' termin dibayar · ':''}${x.contacts?.length||0} kontak · ${x.landRights?.length||0} hak tanah</span></div></div><div><span class="pill ${x.verificationStatus==='sudah_diverifikasi'?'':'warn'}">${x.verificationStatus==='sudah_diverifikasi'?'DIVERIFIKASI':'PERLU VERIFIKASI'}</span></div><div><button onclick="openEdit(${i})">Buka / Edit</button></div></article>`}).join('')}

function addRepeat(id,vals,kind){let html='';if(kind==='contact')html=`<select class=role><option>Pihak Pertama</option><option>Pihak Kedua</option><option>Notaris</option><option>Lainnya</option></select><input class=name placeholder="Nama / PIC" value="${vals.name||''}"><input class=phone placeholder="Telepon" value="${vals.phone||''}"><input class=email placeholder="Email" value="${vals.email||''}">`;if(kind==='bank')html=`<input class=purpose placeholder="Tujuan rekening" value="${vals.purpose||''}"><input class=bank placeholder="Bank" value="${vals.bank||''}"><input class=account placeholder="No. rekening" value="${vals.account||''}"><input class=holder placeholder="Nama pemilik" value="${vals.holder||''}">`;if(kind==='land')html=`<select class=type><option>HGB</option><option>HM</option><option>SHM</option><option>Hak Pakai</option><option>Lainnya</option></select><input class=number placeholder="Nomor" value="${vals.number||''}"><input class=area placeholder="Luas" value="${vals.area||''}"><input type=date class=end value="${vals.end||''}">`;if(kind==='clause')html=`<input class=title placeholder="Judul klausul" value="${vals.title||''}"><input class=detail placeholder="Ringkasan klausul" value="${vals.detail||''}"><input class=page placeholder="Halaman" value="${vals.page||''}"><select class=importance><option>Penting</option><option>Normal</option></select>`;let d=document.createElement('div');d.className='repeat-row '+kind;d.innerHTML=html+'<button type="button" class="secondary" onclick="this.parentElement.remove()">−</button>';$('#'+id).appendChild(d);Object.keys(vals).forEach(k=>{let e=d.querySelector('.'+k);if(e)e.value=vals[k]})}
function pay(p={}){let d=document.createElement('div');d.className='repeat-row payrow';const st=p.status||'unpaid';d.innerHTML=`<input type=date class=due value="${p.due||''}"><input type=text inputmode="decimal" class="amount money-input" placeholder="Rp 0" value="${moneyDisplay(p.amount)}"><input class=label placeholder="Keterangan" value="${p.label||''}"><select class=status><option value="unpaid" ${st!=='paid'?'selected':''}>Belum dibayar</option><option value="paid" ${st==='paid'?'selected':''}>Sudah dibayar</option></select><input type=date class=paidDate value="${p.paidDate||''}" title="Tanggal pembayaran aktual"><button type=button class=secondary>−</button>`;$('#payments').appendChild(d);const statusEl=d.querySelector('.status'),paidDate=d.querySelector('.paidDate');function syncPaid(){paidDate.disabled=statusEl.value!=='paid';if(statusEl.value==='paid'&&!paidDate.value)paidDate.value=new Date().toISOString().slice(0,10);if(statusEl.value!=='paid')paidDate.value=''}statusEl.addEventListener('change',syncPaid);syncPaid();bindMoneyInput(d.querySelector('.amount'),updatePaymentCheck);d.querySelector('button').onclick=()=>{d.remove();updatePaymentCheck()};updatePaymentCheck()}
function updatePaymentCheck(){const box=$('#paymentCheck');if(!box)return;const rent=parseMoney(document.querySelector('[name="rent"]')?.value);const amounts=[...document.querySelectorAll('#payments .amount')].map(e=>parseMoney(e.value));const total=Math.round(amounts.reduce((s,n)=>s+n,0)*100)/100;const count=amounts.filter(n=>n>0).length;if(!rent&&!total){box.innerHTML='';box.className='payment-check muted';return}const diff=Math.round((rent-total)*100)/100;const match=Math.abs(diff)<0.01;const pct=rent?Math.round((total/rent)*10000)/100:0;box.className='payment-check '+(match?'ok':'warn-text');box.innerHTML=`<div class=payment-check-title>${match?'✓ Jadwal pembayaran sesuai dengan nilai sewa':'⚠ Jadwal pembayaran belum sesuai'}</div><div class=payment-check-grid><span><small>Nilai sewa</small><b>Rp ${fmt(rent)}</b></span><span><small>Total ${count} termin</small><b>Rp ${fmt(total)}</b></span><span><small>Selisih</small><b>${match?'Rp 0':(diff>0?'Kurang ':'Lebih ')+'Rp '+fmt(Math.abs(diff))}</b></span><span><small>Terjadwal</small><b>${pct.toLocaleString('id-ID',{maximumFractionDigits:2})}%</b></span></div>`}
function fileToBase64(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(r.error);r.readAsDataURL(file)})}
function setField(name,value){if(value===undefined||value===null||value==='')return;const e=document.querySelector(`[name="${name}"]`);if(!e)return;e.value=e.classList.contains('money-input')?moneyDisplay(value):value}
function applyExtracted(x){
  ['tenant','lessor','asset','propertyAddress','propertyArea','deedNo','deedDate','start','end','rent','deposit','renewalNotice','renewalTerm','sourcePages','notes'].forEach(k=>setField(k,x[k]));
  if(Array.isArray(x.contacts)&&x.contacts.length){$('#contacts').innerHTML='';x.contacts.forEach(v=>addRepeat('contacts',v,'contact'))}
  if(Array.isArray(x.bankAccounts)&&x.bankAccounts.length){$('#banks').innerHTML='';x.bankAccounts.forEach(v=>addRepeat('banks',v,'bank'))}
  if(Array.isArray(x.landRights)&&x.landRights.length){$('#lands').innerHTML='';x.landRights.forEach(v=>addRepeat('lands',v,'land'))}
  if(Array.isArray(x.payments)&&x.payments.length){$('#payments').innerHTML='';x.payments.forEach(v=>pay({...v,status:'unpaid'}))}
  if(Array.isArray(x.clauses)&&x.clauses.length){$('#clauses').innerHTML='';x.clauses.forEach(v=>addRepeat('clauses',v,'clause'))}
  setField('verificationStatus','perlu_verifikasi');$('#verifyBadge').textContent='PERLU VERIFIKASI';updatePaymentCheck();
}
async function extractDocument(){const file=$('#aiFile').files?.[0],btn=$('#extractBtn'),st=$('#extractStatus');if(!file)return alert('Pilih file PDF atau foto scan terlebih dahulu.');if(file.size>18*1024*1024)return alert('File terlalu besar. Maksimum 18 MB untuk pembacaan langsung.');btn.disabled=true;st.textContent='Membaca dokumen dengan AI… jangan tutup halaman ini.';try{const base64=await fileToBase64(file);const {data:out,error}=await sb.functions.invoke('extract-lease',{body:{filename:file.name,mimeType:file.type||'application/pdf',base64}});if(error)throw error;if(!out?.data)throw new Error(out?.error||'Hasil ekstraksi kosong');applyExtracted(out.data);st.textContent='✓ Dokumen selesai dibaca. Periksa semua hasil, terutama angka, tanggal, nomor akta, dan klausul sebelum menyimpan.'}catch(e){console.error(e);st.textContent='Gagal membaca dokumen: '+(e.message||e);alert('Ekstraksi AI gagal. Pastikan Supabase Edge Function extract-lease sudah dipasang dan OPENAI_API_KEY sudah diset.')}finally{btn.disabled=false}}

function openEdit(i=-1){edit=i;let x=i>=0?data[i]:{};$('#form').reset();['contacts','banks','lands','payments','clauses'].forEach(id=>$('#'+id).innerHTML='');[...$('#form').elements].forEach(e=>{if(e.name&&x[e.name]!=null)e.value=(e.classList.contains('money-input')?moneyDisplay(x[e.name]):x[e.name])});(x.contacts||[]).forEach(v=>addRepeat('contacts',v,'contact'));(x.bankAccounts||[]).forEach(v=>addRepeat('banks',v,'bank'));(x.landRights||[]).forEach(v=>addRepeat('lands',v,'land'));(x.payments||[]).forEach(pay);(x.clauses||[]).forEach(v=>addRepeat('clauses',v,'clause'));$('#verifyBadge').textContent=x.verificationStatus==='sudah_diverifikasi'?'SUDAH DIVERIFIKASI':'PERLU VERIFIKASI';$('#dlg').showModal();updatePaymentCheck()}window.openEdit=openEdit;
function collect(sel,fields){return [...document.querySelectorAll(sel)].map(r=>Object.fromEntries(fields.map(f=>[f,r.querySelector('.'+f)?.value||'']))).filter(o=>Object.values(o).some(Boolean))}
$('#addBtn').onclick=()=>openEdit();$('#extractBtn').onclick=extractDocument;$('#cancel').onclick=()=>$('#dlg').close();$('#addPayment').onclick=()=>pay();$('#addContact').onclick=()=>addRepeat('contacts',{},'contact');$('#addBank').onclick=()=>addRepeat('banks',{},'bank');$('#addLand').onclick=()=>addRepeat('lands',{},'land');$('#addClause').onclick=()=>addRepeat('clauses',{},'clause');$('#search').oninput=render;bindMoneyInput(document.querySelector('[name="rent"]'),updatePaymentCheck);bindMoneyInput(document.querySelector('[name="deposit"]'));
$('#form').onsubmit=async e=>{e.preventDefault();let x=Object.fromEntries(new FormData(e.target));x.rent=parseMoney(x.rent);x.deposit=parseMoney(x.deposit);x.contacts=collect('#contacts .contact',['role','name','phone','email']);x.bankAccounts=collect('#banks .bank',['purpose','bank','account','holder']);x.landRights=collect('#lands .land',['type','number','area','end']);x.clauses=collect('#clauses .clause',['title','detail','page','importance']);x.payments=collect('#payments .payrow',['due','amount','label','status','paidDate']).map(p=>({...p,amount:parseMoney(p.amount)}));if(edit>=0&&data[edit]?.id)x.id=data[edit].id;let b=e.submitter;try{b.disabled=true;await saveContract(x);$('#dlg').close()}catch(err){alert('Gagal menyimpan: '+err.message)}finally{b.disabled=false}};
if('serviceWorker'in navigator)navigator.serviceWorker.getRegistrations().then(rs=>rs.forEach(r=>r.unregister())).catch(()=>{});initAuth();
