-- PALM v1.21.11 RC Corrected 2 — Warning Email Settings + Daily Digest
-- Jalankan sekali di Supabase SQL Editor sebelum mengaktifkan email warning.

alter table public.app_user_access
  add column if not exists warning_email_enabled boolean not null default false,
  add column if not exists warning_email text;

-- Isi alamat default dari email login, tetapi TIDAK mengaktifkan pengiriman.
update public.app_user_access a
set warning_email=u.email
from auth.users u
where u.id=a.user_id and (a.warning_email is null or btrim(a.warning_email)='');

create table if not exists public.app_warning_email_log (
  id bigint generated by default as identity primary key,
  data_owner_id uuid not null references auth.users(id) on delete cascade,
  recipient_user_id uuid not null references auth.users(id) on delete cascade,
  recipient_email text not null,
  warning_key text not null,
  warning_stage text not null,
  warning_type text not null,
  warning_text text not null,
  due_date date,
  sent_at timestamptz not null default now(),
  unique(recipient_user_id,warning_key,warning_stage)
);
alter table public.app_warning_email_log enable row level security;
drop policy if exists warning_email_log_admin_select on public.app_warning_email_log;
create policy warning_email_log_admin_select on public.app_warning_email_log for select to authenticated
using (data_owner_id=public.app_access_owner() and public.app_is_admin());

drop function if exists public.app_list_users();
create or replace function public.app_list_users()
returns table(id uuid,email text,role text,data_owner_id uuid,warning_email_enabled boolean,warning_email text)
language plpgsql security definer set search_path=public,auth as $$
begin
 if not public.app_is_admin() then raise exception 'Administrator only'; end if;
 return query select u.id,u.email::text,a.role,a.data_owner_id,a.warning_email_enabled,a.warning_email
 from public.app_user_access a join auth.users u on u.id=a.user_id
 where a.data_owner_id=public.app_access_owner()
 order by case a.role when 'administrator' then 1 when 'document_manager' then 2 else 3 end,u.email;
end$$;

create or replace function public.app_update_warning_email(target_user_id uuid,target_enabled boolean,target_email text)
returns void language plpgsql security definer set search_path=public as $$
declare v_email text;
begin
 if not public.app_is_admin() then raise exception 'Administrator only'; end if;
 if not exists(select 1 from public.app_user_access where user_id=target_user_id and data_owner_id=public.app_access_owner()) then raise exception 'User bukan anggota workspace ini'; end if;
 v_email := nullif(lower(btrim(target_email)), '');
 if coalesce(target_enabled,false) and (v_email is null or position('@' in v_email) <= 1 or position('.' in split_part(v_email,'@',2)) <= 1) then raise exception 'Alamat email tidak valid'; end if;
 update public.app_user_access set warning_email_enabled=coalesce(target_enabled,false),warning_email=v_email,updated_at=now() where user_id=target_user_id;
end$$;
revoke all on function public.app_update_warning_email(uuid,boolean,text) from public;
grant execute on function public.app_update_warning_email(uuid,boolean,text) to authenticated;

-- Edge Function send-warning-emails membaca tabel dengan SUPABASE_SERVICE_ROLE_KEY.
-- Secrets yang harus dibuat di Supabase Edge Functions:
-- RESEND_API_KEY, WARNING_FROM_EMAIL, WARNING_CRON_SECRET.
-- Jadwalkan pemanggilan function 1x per hari (disarankan pagi WIB) dan kirim header:
-- Authorization: Bearer <WARNING_CRON_SECRET>
