-- Sewa & Akta Tanah v1.19.31 RC
-- Tidak ada perubahan schema/database yang perlu dijalankan untuk versi ini.
-- Perubahan v1.19.31 berada pada pipeline AI PBB dan logika aplikasi untuk menyimpan histori pembayaran per NOP+tahun.
