import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const SUPABASE_URL=Deno.env.get('SUPABASE_URL')||''
const SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||''
const RESEND_API_KEY=Deno.env.get('RESEND_API_KEY')||''
const FROM=Deno.env.get('WARNING_FROM_EMAIL')||''
const CRON_SECRET=Deno.env.get('WARNING_CRON_SECRET')||''
const sb=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false}})
const rupiah=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n||0)
const esc=(s:any)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c))
const today=()=>{const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());return p}
const dayDiff=(iso:string)=>{if(!iso)return 999999;const a=new Date(today()+'T00:00:00+07:00'),b=new Date(iso+'T00:00:00+07:00');return Math.round((b.getTime()-a.getTime())/86400000)}
const kind=(p:any)=>{const k=String(p.kind||p.type||'').toLowerCase(),l=String(p.label||'').toLowerCase();if(['deposit','security_deposit'].includes(k)||/security\s*deposit|deposit/.test(l))return'deposit';if(['pbb','pbb_reimbursement','other','lainnya'].includes(k)||/penggantian\s*pbb|reimburse.*pbb/.test(l))return'other';return'rent'}
const target=(c:any,p:any)=>{const n=Number(p.amount||0);if(kind(p)!=='rent')return n;const rate=Math.max(0,Math.min(100,Number(c.payments_meta?.rentTaxRate||0)));return (c.payments_meta?.rentTaxMode||'gross_includes_tax')==='gross_includes_tax'?Math.max(0,n-Math.round(n*rate/100)):n}
function ledger(payments:any[]){const out:any[]=[],seen=new Set<string>();let legacy=0;for(const p of payments||[])for(const t of (Array.isArray(p.transactions)&&p.transactions.length?p.transactions:(p.status==='paid'&&Number(p.amount||0)>0?[{date:p.paidDate||'',amount:Number(p.amount||0)}]:[]))){const id=String(t.ledgerId||`legacy_${legacy++}`);if(seen.has(id))continue;seen.add(id);out.push({...t,id,kind:t.kind||kind(p),targetId:t.targetId||'',amount:Number(t.originalAmount??t.amount)||0})}return out}
function paymentStates(c:any){const ps=Array.isArray(c.payments)?c.payments:[],st=ps.map((p:any)=>({p,target:target(c,p),paid:0,remaining:target(c,p)}));for(const t of ledger(ps)){let left=t.amount,k=t.kind;if(left<=0)continue;if(t.targetId){const i=ps.findIndex((p:any)=>String(p.id||'')===String(t.targetId)&&kind(p)===k);if(i>=0&&st[i].remaining>1){const part=Math.min(left,st[i].remaining);st[i].paid+=part;st[i].remaining-=part;left-=part;if(st[i].remaining<=1)st[i].remaining=0}}for(let i=0;i<ps.length&&left>1;i++){if(kind(ps[i])!==k||st[i].remaining<=1)continue;const part=Math.min(left,st[i].remaining);st[i].paid+=part;st[i].remaining-=part;left-=part;if(st[i].remaining<=1)st[i].remaining=0}}return st}
function stage(days:number,bounds:number[]){if(days<0)return'overdue';for(const b of [...bounds].sort((a,b)=>a-b))if(days<=b)return`h${b}`;return''}
type W={key:string;stage:string;type:string;text:string;due:string|null;days:number}
function warnings(contracts:any[],titles:any[],pbb:any[]):W[]{const out:W[]=[];const add=(key:string,days:number,bounds:number[],type:string,text:string,due:string|null)=>{const s=stage(days,bounds);if(s)out.push({key,stage:s,type,text,due,days})};
 for(const c of contracts){for(const {p,target,paid,remaining} of paymentStates(c)){if(!p.due||remaining<=0)continue;const k=kind(p),noun=k==='rent'?'netto':'kewajiban',detail=paid>0?`Kurang bayar ${rupiah(remaining)} dari ${noun} ${rupiah(target)} (diterima ${rupiah(paid)})`:`Belum dibayar ${noun} ${rupiah(target)}`,type=k==='deposit'?'SECURITY DEPOSIT':k==='other'?'PEMBAYARAN LAIN-LAIN':'PEMBAYARAN SEWA';add(`pay:${c.id}:${p.id||p.due}:${k}`,dayDiff(p.due),[0,1,3,7,14,30,90],type,`${detail} · ${c.tenant||'-'} — jatuh tempo ${p.due}`,p.due)}
  if(c.end_date)add(`contract:${c.id}`,dayDiff(c.end_date),[0,1,3,7,14,30,60,180],'KONTRAK',`Kontrak ${c.tenant||'-'} berakhir ${c.end_date}. Siapkan perpanjangan / kontrak baru.`,c.end_date);
  if(c.renewal_notice)add(`renewal:${c.id}`,dayDiff(c.renewal_notice),[0,1,3,7,14,30,60,365],'PERPANJANGAN',`Deadline pemberitahuan perpanjangan ${c.tenant||'-'} — ${c.renewal_notice}`,c.renewal_notice)
 }
 for(const t of titles||[]){if(!t.valid_until)continue;const label=`${t.right_type||'Hak Tanah'} ${t.certificate_no||'-'}`;add(`land:${t.id}`,dayDiff(t.valid_until),[0,1,3,7,14,30,90,180,365,730,1095],'HAK TANAH',`${label} berakhir ${t.valid_until}. Tindak lanjuti persiapan/perpanjangan.`,t.valid_until)}
 const latest=new Map<string,any>();for(const r of pbb||[]){const k=String(r.nop||r.id),old=latest.get(k);if(!old||Number(r.tax_year||0)>Number(old.tax_year||0))latest.set(k,r)}for(const r of latest.values()){if(r.payment_status==='lunas'||r.warning_ignored||!r.due_date)continue;add(`pbb:${r.id}`,dayDiff(r.due_date),[0,1,3,7,14,30,90],'PBB',`PBB ${r.tax_year||''} · NOP ${r.nop||'-'} · ${rupiah(Number(r.pbb_payable??r.pbb_due??0))} · jatuh tempo ${r.due_date}`,r.due_date)}return out}
function statusLabel(w:W){return w.days<0?`TERLAMBAT ${Math.abs(w.days)} HARI`:w.days===0?'HARI INI':`H-${w.days}`}
function groupRank(w:W){if(w.days<0)return 0;if(w.days===0)return 1;if(w.days<=3)return 2;if(w.days<=7)return 3;if(w.days<=14)return 4;if(w.days<=30)return 5;return 6}
async function sendDigest(to:string,items:W[]){
 const sorted=[...items].sort((a,b)=>groupRank(a)-groupRank(b)||a.days-b.days||a.type.localeCompare(b.type,'id'))
 const groups=[
  ['TERLAMBAT',sorted.filter(w=>w.days<0)],['HARI INI',sorted.filter(w=>w.days===0)],['H-1 s.d. H-3',sorted.filter(w=>w.days>0&&w.days<=3)],['H-4 s.d. H-7',sorted.filter(w=>w.days>3&&w.days<=7)],['H-8 s.d. H-14',sorted.filter(w=>w.days>7&&w.days<=14)],['H-15 s.d. H-30',sorted.filter(w=>w.days>14&&w.days<=30)],['PERINGATAN AWAL',sorted.filter(w=>w.days>30)]
 ] as [string,W[]][]
 const sections=groups.filter(([,ws])=>ws.length).map(([label,ws])=>`<h3 style="margin:22px 0 8px">${esc(label)} (${ws.length})</h3><table style="width:100%;border-collapse:collapse">${ws.map(w=>`<tr><td style="padding:10px 8px;border-top:1px solid #ddd;vertical-align:top"><b>${esc(w.type)}</b><br><span>${esc(w.text)}</span>${w.due?`<br><small>Tanggal terkait: <b>${esc(w.due)}</b> · ${esc(statusLabel(w))}</small>`:''}</td></tr>`).join('')}</table>`).join('')
 const subject=`PALM — ${items.length} Peringatan Memerlukan Perhatian`
 const html=`<div style="font-family:Arial,sans-serif;line-height:1.5;max-width:760px;margin:auto"><h2>Property Asset &amp; Legal Management</h2><p>Ringkasan peringatan PALM tanggal <b>${esc(today())}</b>. Terdapat <b>${items.length}</b> peringatan baru pada tahap reminder yang perlu diperhatikan.</p>${sections}<hr><small>Email otomatis PALM. Maksimal satu ringkasan per penerima per proses harian. Warning yang sama pada tahap yang sama tidak dikirim ulang. Pengaturan penerima dapat diubah Administrator melalui menu User.</small></div>`
 const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:FROM,to:[to],subject,html})});if(!r.ok)throw new Error(`Email API ${r.status}: ${await r.text()}`)
}
Deno.serve(async req=>{if(!CRON_SECRET||req.headers.get('authorization')!==`Bearer ${CRON_SECRET}`)return new Response('Unauthorized',{status:401});if(!SUPABASE_URL||!SERVICE_KEY||!RESEND_API_KEY||!FROM)return new Response('Missing server secrets',{status:500});
 const {data:recipients,error:re}=await sb.from('app_user_access').select('user_id,data_owner_id,warning_email_enabled,warning_email').eq('warning_email_enabled',true).not('warning_email','is',null);if(re)throw re;let emailsSent=0,warningsSent=0,skipped=0,failed=0;
 const owners=[...new Set((recipients||[]).map((r:any)=>r.data_owner_id))];for(const owner of owners){const [c,t,p]=await Promise.all([sb.from('contracts').select('id,user_id,tenant,end_date,renewal_notice,payments,payments_meta').eq('user_id',owner),sb.from('land_titles').select('id,user_id,right_type,certificate_no,valid_until').eq('user_id',owner),sb.from('pbb_records').select('id,user_id,nop,tax_year,payment_status,warning_ignored,due_date,pbb_payable,pbb_due').eq('user_id',owner)]);if(c.error||t.error||p.error){failed++;continue}const ws=warnings(c.data||[],t.data||[],p.data||[]);
  for(const r of (recipients||[]).filter((x:any)=>x.data_owner_id===owner)){const pending:W[]=[];for(const w of ws){const {data:exists,error:ee}=await sb.from('app_warning_email_log').select('id').eq('recipient_user_id',r.user_id).eq('warning_key',w.key).eq('warning_stage',w.stage).maybeSingle();if(ee){failed++;continue}if(exists){skipped++;continue}pending.push(w)}if(!pending.length)continue;
   try{await sendDigest(r.warning_email,pending);const rows=pending.map(w=>({data_owner_id:owner,recipient_user_id:r.user_id,recipient_email:r.warning_email,warning_key:w.key,warning_stage:w.stage,warning_type:w.type,warning_text:w.text,due_date:w.due}));const ins=await sb.from('app_warning_email_log').insert(rows);if(ins.error)throw ins.error;emailsSent++;warningsSent+=pending.length}catch(e){console.error(e);failed++}
  }}
 return Response.json({ok:true,date:today(),emails_sent:emailsSent,warnings_sent:warningsSent,skipped,failed})})
